### ISSUE TITLE
Cannot find module '.../build/main.js' from 'build/_fake.js'

### ISSUE THREAD

**Issue by l00sed** [y-naught/NURBSJS#1]
Looks like the `compile.sh` script is trying to minify a `main.js` file that seems to no longer exist--- perhaps there used to be a `main.ts` file in /src? Can't get specified startup code to run with the directions in the README.md.

**Comment by y-naught** [comment]
Thanks for catching that. There was a main.js file in the build folder that was getting referenced directly rather than being built from a TypeScript file during the trans-pile operation. Should be good to go now.
